# The FQDN hosting fudge. If the `git-url` config option is set, this option
# will be used as an import path prefix for `go-import` meta tags.
domain: fudge.example.org

# The URL of a public facing Git server hosting your repositories. If this
# option is set, it will be used as a prefix for clone URLs and as a repository
# root for `go-import` meta tags.
#
# Examples:
#   git-url: https://github.com/username
#   git-url: https://git.example.org
git-url:

# The path to search for Git repositories in. Fudge will *not* recurse into its
# subdirectories.
repo-root: /home/git/

# If set to `true`, the application will run in debug mode.
debug: false

# The description of each Git repository.
descriptions:
  simple: A simple description
  multi-line: |
    A multiline description.
    This is the second line.

loggers:
  router:
    # If set to `true`, requests made to the router will be logged in Apache's
    # Combined Log Format.
    enable: false
    # The logger's mode. Available modes are: stdout, stderr, file, and syslog.
    mode:
    # If `mode` is set to "file", this option will be used as the log file
    # path. If the file exists, it will be opened in append mode. Otherwise, it
    # will be created with 0644 permissions. Fudge will not rotate log files,
    # please use an external program like logrotate or newsyslog to do so.
    path:
    # If `mode` is set to "syslog", this option will be used as the syslog
    # priority. Available priorities are: emerg, alert, crit, err, warning,
    # notice, info, and debug.
    priority:
